# Set global options
data_dir: /tmp/vector

sources:
  vector_log:
    type: internal_logs

sinks:
  print_openwrt_log:
    type: console
    inputs:
      - vector_log
    encoding:
      codec: text