# Set global options
data_dir: /tmp/vector

api:
  address: 0.0.0.0:8686
  enabled: true

sources:
  vector_log:
    type: internal_logs

sinks:
  vector_stdout:
    type: console
    inputs:
      - vector_log
    encoding:
      codec: text
