#!/bin/sh /etc/rc.common

START=80
STOP=15
USE_PROCD=1
APP=vector

start_service() {
  local config_file
  local std_err std_out
  local verbose

  config_load $APP
  config_get_bool std_out "main" log_stdout 1
  config_get_bool std_err "main" log_stderr 1
  config_get_bool verbose "main" log_stderr 1
  config_get config_file "main" config_file /etc/vector/config.yml

  # Default data storage path
  mkdir -p tmp/vector

  # Validate
  /usr/bin/vector validate "$config_file"

  procd_open_instance
  procd_set_param command /usr/bin/$APP
  procd_append_param command --config "$config_file"
  [ "${verbose}" -eq 1 ] && procd_append_param command --verbose

  procd_set_param respawn
  procd_set_param stdout "$std_out"
  procd_set_param stderr "$std_err"

  procd_close_instance
}

stop_service() {
  service_stop /usr/bin/$APP
}

service_triggers() {
	procd_add_reload_trigger "$APP"
}