# Set global options
data_dir: /tmp/vector

sources:
  openwrt_log:
    type: exec
    mode: scheduled
    command: logread

sinks:
  print_openwrt_log:
    type: console
    inputs:
      - openwrt_log
    encoding:
      codec: text
